[package]
name = "soroban-cli"
description = "Soroban CLI"
homepage = "https://github.com/stellar/soroban-cli"
repository = "https://github.com/stellar/soroban-cli"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
readme = "README.md"
version = "0.0.2"
edition = "2021"
rust-version = "1.63"

[dependencies]
soroban-env-host = { version = "0.0.4", features = ["vm", "serde"] }
soroban-spec = "0.0.4"
stellar-strkey = "0.0.1"
clap = { version = "3.1.18", features = ["derive", "env"] }
base64 = "0.13.0"
thiserror = "1.0.31"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.82"
hex = "0.4.3"
num-bigint = "0.4"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
clap_complete = "3.2.3"
prettyplease = "0.1.18"
syn = { version = "1.0.99", features = ["parsing"] }
wasmparser = "0.90.0"
sha2 = "0.10.2"

[patch.crates-io]
soroban-spec = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "ad77b1f" }
stellar-strkey = { git = "https://github.com/stellar/rs-stellar-strkey", rev = "317f7689" }
soroban-env-common = { git = "https://github.com/stellar/rs-soroban-env", rev = "c8bc71d" }
soroban-env-host = { git = "https://github.com/stellar/rs-soroban-env", rev = "c8bc71d" }
soroban-env-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "c8bc71d" }
soroban-native-sdk-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "c8bc71d" }
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "fee9a43" }
