[package]
name = "stellar-contract-cli"
version = "0.0.0"
edition = "2021"

[dependencies]
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", branch = "add-spec", features = ["next", "std"] }
stellar-contract-env-host = { git = "https://github.com/stellar/rs-stellar-contract-env", rev = "5e6bd28f", features = ["vm"] }
# stellar-contract-env-host = { path = "../rs-stellar-contract-env/stellar-contract-env-host", features = ["vm"] }
clap = { version = "3.1.18", features = ["derive", "env"] }
base64 = "0.13.0"
thiserror = "1.0.31"
