[package]
name = "soroban-cli"
description = "Soroban CLI"
homepage = "https://github.com/stellar/soroban-cli"
repository = "https://github.com/stellar/soroban-cli"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
readme = "README.md"
version = "0.0.4"
edition = "2021"
rust-version = "1.64"

[dependencies]
soroban-env-host = { version = "0.0.5", features = ["vm", "serde", "hostfn_log_fmt_values"] }
soroban-spec = "0.0.4"
stellar-strkey = "0.0.2"
clap = { version = "3.1.18", features = ["derive", "env"] }
base64 = "0.13.0"
thiserror = "1.0.31"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.82"
hex = "0.4.3"
num-bigint = "0.4"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
clap_complete = "3.2.3"
prettyplease = "0.1.18"
rand = "0.8.5"
syn = { version = "1.0.99", features = ["parsing"] }
wasmparser = "0.90.0"
sha2 = "0.10.6"
csv = "1.1.6"
ed25519-dalek = "1.0.1"
jsonrpsee-http-client = "0.15.1"
jsonrpsee-core = "0.15.1"

[patch.crates-io]
soroban-spec = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "bc3ff723" }
stellar-strkey = { git = "https://github.com/stellar/rs-stellar-strkey", rev = "3c21b987" }
soroban-env-common = { git = "https://github.com/stellar/rs-soroban-env", rev = "b20d10db" }
soroban-env-host = { git = "https://github.com/stellar/rs-soroban-env", rev = "b20d10db" }
soroban-env-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "b20d10db" }
soroban-native-sdk-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "b20d10db" }
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "1bcc6fe3" }
wasmi = { package = "soroban-wasmi", git = "https://github.com/stellar/wasmi", rev = "a61b6df" }

# soroban-env-common = { path = "../rs-soroban-env/soroban-env-common" }
# soroban-env-host = { path = "../rs-soroban-env/soroban-env-host" }
# soroban-env-macros = { path = "../rs-soroban-env/soroban-env-macros" }
# soroban-native-sdk-macros = { path = "../rs-soroban-env/soroban-native-sdk-macros" }
