[workspace]
resolver = "2"
members = [
    "cmd/soroban-cli",
    "cmd/soroban-cli/tests/fixtures/test-wasms/*",
    "cmd/soroban-rpc/lib/preflight",
]
default-members = ["cmd/soroban-cli"]

[workspace.dependencies.soroban-env-host]
version = "0.0.12"
git = "https://github.com/stellar/rs-soroban-env"
rev = "360069b8cce745208244e53171d18ace69650052"

[workspace.dependencies.soroban-spec]
version = "0.4.1"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "d801de53b67a190658b48aab21a6aea3adb83ffc"

[workspace.dependencies.soroban-token-spec]
version = "0.4.1"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "d801de53b67a190658b48aab21a6aea3adb83ffc"

[workspace.dependencies.soroban-sdk]
version = "0.4.1"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "d801de53b67a190658b48aab21a6aea3adb83ffc"

[workspace.dependencies.soroban-ledger-snapshot]
version = "0.4.1"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "d801de53b67a190658b48aab21a6aea3adb83ffc"

[workspace.dependencies.stellar-strkey]
version = "0.0.7"
git = "https://github.com/stellar/rs-stellar-strkey"
rev = "e6ba45c60c16de28c7522586b80ed0150157df73"

# [patch."https://github.com/stellar/rs-soroban-env"]
# soroban-env-host = { path = "../rs-soroban-env/soroban-env-host/" }
# [patch."https://github.com/stellar/rs-soroban-sdk"]
# soroban-spec = { path = "../rs-soroban-sdk/soroban-spec/" }
# soroban-token-spec = { path = "../rs-soroban-sdk/soroban-token-spec/" }
# soroban-sdk = { path = "../rs-soroban-sdk/soroban-sdk/" }
# [patch."https://github.com/stellar/rs-stellar-xdr"]
# stellar-xdr = { path = "../rs-stellar-xdr/" }

[profile.test-wasms]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-panic-unwind]
inherits = 'release'
panic = 'unwind'
