[package]
name = "soroban-cli"
description = "Soroban CLI"
homepage = "https://github.com/stellar/soroban-cli"
repository = "https://github.com/stellar/soroban-cli"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
readme = "README.md"
version = "0.0.2"
edition = "2021"

[dependencies]
soroban-env-host = { version = "0.0.3", features = ["vm", "serde"] }
# soroban-spec = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "04d4358f" }
soroban-spec = { path = "../rs-soroban-sdk/soroban-spec" }
stellar-strkey = { git = "https://github.com/stellar/rs-stellar-strkey", rev = "99dfcf8" }
clap = { version = "3.1.18", features = ["derive", "env"] }
base64 = "0.13.0"
thiserror = "1.0.31"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.82"
hex = "0.4.3"
num-bigint = "0.4"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
clap_complete = "3.2.3"
prettyplease = "0.1.18"
syn = { version = "1.0.99", features = ["parsing"] }

[patch.crates-io]
soroban-env-common = { git = "https://github.com/stellar/rs-soroban-env", rev = "556c75f" }
soroban-env-host = { git = "https://github.com/stellar/rs-soroban-env", rev = "556c75f" }
soroban-env-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "556c75f" }
soroban-native-sdk-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "556c75f" }
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "3eca5ce" }
