[workspace]
members = [
    ".",
    "test-wasms/invoker_account_exists"
]

[package]
name = "soroban-cli"
description = "Soroban CLI"
homepage = "https://github.com/stellar/soroban-cli"
repository = "https://github.com/stellar/soroban-cli"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
readme = "README.md"
version = "0.1.2"
edition = "2021"
rust-version = "1.64"
autobins = false
build = "build.rs"

[build-dependencies]
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.82"

[[bin]]
name = "soroban"
path = "src/main.rs"

[dependencies]
soroban-env-host = { version = "0.0.6", features = ["vm", "serde", "hostfn_log_fmt_values"] }
soroban-spec = "0.1.0"
soroban-token-spec = "0.1.0"
soroban-auth = "0.1.0"
stellar-strkey = "0.0.6"
clap = { version = "3.1.18", features = ["derive", "env"] }
base64 = "0.13.0"
thiserror = "1.0.31"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.82"
hex = "0.4.3"
num-bigint = "0.4"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
clap_complete = "3.2.3"
rand = "0.8.5"
wasmparser = "0.90.0"
sha2 = "0.10.6"
csv = "1.1.6"
ed25519-dalek = "1.0.1"
jsonrpsee-http-client = "0.15.1"
jsonrpsee-core = "0.15.1"
regex = "1.6.0"

[dev_dependencies]
assert_cmd = "2.0.4"
assert_fs = "1.0.7"

[patch.crates-io]
soroban-spec = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "b66355c4" }
soroban-token-spec = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "b66355c4" }
soroban-auth = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "b66355c4" }
soroban-sdk = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "b66355c4" }
soroban-sdk-macros = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "b66355c4" }
stellar-strkey = { git = "https://github.com/stellar/rs-stellar-strkey", rev = "d1b68fd1" }
soroban-env-common = { git = "https://github.com/stellar/rs-soroban-env", rev = "4f2f3a2d" }
soroban-env-guest = { git = "https://github.com/stellar/rs-soroban-env", rev = "4f2f3a2d" }
soroban-env-host = { git = "https://github.com/stellar/rs-soroban-env", rev = "4f2f3a2d" }
soroban-env-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "4f2f3a2d" }
soroban-native-sdk-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "4f2f3a2d" }
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "3ba13687" }
wasmi = { package = "soroban-wasmi", git = "https://github.com/stellar/wasmi", rev = "d1ec0036" }

# soroban-env-common = { path = "../rs-soroban-env/soroban-env-common" }
# soroban-env-host = { path = "../rs-soroban-env/soroban-env-host" }
# soroban-env-macros = { path = "../rs-soroban-env/soroban-env-macros" }
# soroban-native-sdk-macros = { path = "../rs-soroban-env/soroban-native-sdk-macros" }

[profile.test-wasms]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
