[workspace]
resolver = "2"
members = [
    "cmd/soroban-cli",
    "cmd/crates/*",
    "cmd/crates/soroban-test/tests/fixtures/test-wasms/*",
    "cmd/crates/soroban-test/tests/fixtures/hello",
    "cmd/soroban-rpc/lib/preflight",
]
default-members = ["cmd/soroban-cli", "cmd/crates/soroban-test"]
exclude = ["cmd/crates/soroban-test/tests/fixtures/hello"]

[workspace.dependencies.soroban-env-host]
version = "0.0.15"
git = "https://github.com/stellar/rs-soroban-env"
rev = "bad318a9805cf25ae64afb5122cb37af67a2edbd"

[workspace.dependencies.soroban-spec]
version = "0.7.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "c39aad350e9c1e49105118058c75f8f0d7237b2b"

[workspace.dependencies.soroban-sdk]
version = "0.7.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "c39aad350e9c1e49105118058c75f8f0d7237b2b"

[workspace.dependencies.soroban-ledger-snapshot]
version = "0.7.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "c39aad350e9c1e49105118058c75f8f0d7237b2b"

[workspace.dependencies.soroban-cli]
version = "0.7.1"
path = "cmd/soroban-cli"


[workspace.dependencies]
ethnum = "1.3.2"
sep5 = "0.0.2"
stellar-strkey = "0.0.7"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tracing-appender = "0.2.2"
which = "4.4.0"


# [patch."https://github.com/stellar/rs-soroban-env"]
# soroban-env-host = { path = "../rs-soroban-env/soroban-env-host/" }
# [patch."https://github.com/stellar/rs-soroban-sdk"]
# soroban-spec = { path = "../rs-soroban-sdk/soroban-spec/" }
# soroban-token-spec = { path = "../rs-soroban-sdk/soroban-token-spec/" }
# soroban-sdk = { path = "../rs-soroban-sdk/soroban-sdk/" }
# [patch."https://github.com/stellar/rs-stellar-xdr"]
# stellar-xdr = { path = "../rs-stellar-xdr/" }

[profile.test-wasms]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = true
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-panic-unwind]
inherits = 'release'
panic = 'unwind'
