[workspace]
resolver = "2"
members = [
    "cmd/soroban-cli",
    "cmd/crates/*",
    "cmd/crates/soroban-test/tests/fixtures/test-wasms/*",
    "cmd/crates/soroban-test/tests/fixtures/hello",
    "cmd/soroban-rpc/lib/preflight",
]
default-members = ["cmd/soroban-cli", "cmd/crates/soroban-test"]
exclude = ["cmd/crates/soroban-test/tests/fixtures/hello"]

[workspace.dependencies.soroban-env-host]
version = "0.0.15"
git = "https://github.com/stellar/rs-soroban-env"
rev = "5ef87058f07ad67eeba4c350a6b6af82bd17f916"

[workspace.dependencies.soroban-spec]
version = "0.7.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "29b505cf95f2fd4fbe639fdb163b606c44920837"


[workspace.dependencies.soroban-token-spec]
version = "0.7.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "29b505cf95f2fd4fbe639fdb163b606c44920837"


[workspace.dependencies.soroban-sdk]
version = "0.7.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "29b505cf95f2fd4fbe639fdb163b606c44920837"

[workspace.dependencies.soroban-ledger-snapshot]
version = "0.7.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "29b505cf95f2fd4fbe639fdb163b606c44920837"

[workspace.dependencies.stellar-strkey]
version = "0.0.7"

[workspace.dependencies.sep5]
version = "0.0.2"

[workspace.dependencies.soroban-cli]
version = "0.7.1"
path = "cmd/soroban-cli"

[workspace.dependencies.ethnum]
version = "1.3.2"

[workspace.dependencies.which]
version = "4.4.0"


# [patch."https://github.com/stellar/rs-soroban-env"]
# soroban-env-host = { path = "../rs-soroban-env/soroban-env-host/" }
# [patch."https://github.com/stellar/rs-soroban-sdk"]
# soroban-spec = { path = "../rs-soroban-sdk/soroban-spec/" }
# soroban-token-spec = { path = "../rs-soroban-sdk/soroban-token-spec/" }
# soroban-sdk = { path = "../rs-soroban-sdk/soroban-sdk/" }
# [patch."https://github.com/stellar/rs-stellar-xdr"]
# stellar-xdr = { path = "../rs-stellar-xdr/" }

[profile.test-wasms]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-panic-unwind]
inherits = 'release'
panic = 'unwind'
