[workspace]
resolver = "2"
members = [
    "cmd/soroban-cli",
    "cmd/soroban-cli/tests/fixtures/test-wasms/hello_world",
    "cmd/soroban-cli/tests/fixtures/test-wasms/invoker_account_exists",
]
default-members = ["cmd/soroban-cli"]

[workspace.dependencies.soroban-env-host]
version = "0.0.10"
git = "https://github.com/stellar/rs-soroban-env"
rev = "c148051"

[workspace.dependencies.soroban-spec]
version = "0.3.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "501379d"

[workspace.dependencies.soroban-token-spec]
version = "0.3.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "501379d"

[workspace.dependencies.soroban-sdk]
version = "0.3.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "501379d"

[workspace.dependencies.stellar-strkey]
version = "0.0.6"
git = "https://github.com/stellar/rs-stellar-strkey"
rev = "5e582a8"

# [patch."https://github.com/stellar/rs-soroban-env"]
# soroban-env-host = { path = "../rs-soroban-env/soroban-env-host/" }
# [patch."https://github.com/stellar/rs-soroban-sdk"]
# soroban-spec = { path = "../rs-soroban-sdk/soroban-spec/" }
# soroban-token-spec = { path = "../rs-soroban-sdk/soroban-token-spec/" }
# soroban-sdk = { path = "../rs-soroban-sdk/soroban-sdk/" }
# [patch."https://github.com/stellar/rs-stellar-xdr"]
# stellar-xdr = { path = "../rs-stellar-xdr/" }

[profile.test-wasms]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
