[package]
name = "soroban-cli"
version = "0.0.0"
edition = "2021"

[dependencies]
soroban-env-host = { git = "https://github.com/stellar/rs-stellar-contract-env", rev = "36a5007", features = ["vm", "serde"] }
# switch to this once all the repos are renamed
# soroban-env-host = { git = "https://github.com/stellar/rs-soroban-env", rev = "36a5007", features = ["vm", "serde"] }
# soroban-env-host = { path = "../rs-soroban-env/soroban-env-host", features = ["vm", "serde"] }
clap = { version = "3.1.18", features = ["derive", "env"] }
base64 = "0.13.0"
thiserror = "1.0.31"
serde_json = "1.0.82"
hex = "0.4.3"
